### PR TITLE
Code review requested for the New York Times project

### PR DESCRIPTION
**Pull request by patriciachrysy**

### CODE REVIEW

**Review by rOluochKe — COMMENTED** [review]
### Under review...

**Review by rOluochKe — CHANGES_REQUESTED** [review]
@patriciachrysy and @javitocor 
### Good job, this is impressive, however, there are a few changes you need to make before the project is approved.
- Use html5 semantics where applicable, ie use of `<section></section>` to have a block of code, `<article></article>` for a subsection etc
- Add .gitignore file in your root folder and prevent files like .vscode from being pushed to your repository [check this guide](https://microverse.pathwright.com/library/fast-track)

**In case you are having any difficulty, you can always reach out for help on slack, your team, mentor and any TSE**

### Once you make all these changes, resubmit your project for review. All the best in the next submission.

**Comment by patriciachrysy** [comment]
Created the .gitignore file and deletes the .vscode folder on the repository. Also added the .vscode in the gitignore.
We also wrapped some code with the section and article tags.

**Comment by euqueme** [comment]
## Hello @patriciachrysy  and @javitocor  :bulb:
### Great job doing the changes requested by the previous reviewer, your page looks amazing :art: :eyes:

### Just a couple of requirements and you will be good to go :athletic_shoe: 

**Bottom part**

* [ ] in the **More in Space and Astronomy** section I see you already have the images with its captions but you have to put them inside \<a\> tags ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))

**Readme file**
- [ ] You have a broken image in your Readme file

image

- [ ]  Your Live Demo Link takes you back to the project page please follow these [steps](https://help.github.com/en/enterprise/2.13/user/articles/configuring-a-publishing-source-for-github-pages) to make a Live Demo within your repository.

### That's it. Please :pray: correct these changes and submit back for a code review when you are done :rocket:

### Good spirit! :muscle:

STATUS OF THE PROJECT: REQUESTED CHANGES :traffic_light:

**Comment by patriciachrysy** [comment]
Changes applied according to the latest review. 
However, the icons are not displaying in the githack Livelink, while they are displaying locally in our browser. Sure it will appear in the GitHub pages Livelink(already generated) as soon as we merge to the master branch.

**Review by suretrust — APPROVED** [review]
Hi team, 👋 

### Great job implementing the TSEs' suggestions. 🙌 Let's get this merged! 👍 

_Good luck with your future projects and happy coding!_ 🎉

**Pull request merged**
